# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab:

Vagrant::Config.run do |config|

  box = "precise32"

  config.vm.define :rabbitmq do |rabbit_config|
    #rabbit_config.vm.boot_mode = :gui
    rabbit_config.vm.box = box
    config.vm.network :hostonly, "192.168.64.10"
    rabbit_config.vm.provision :shell, :path => "rabbitmq.sh"
    rabbit_config.vm.customize do |vm|
      vm.name = "nexiles - rabbitmq"
    end
  end
end